**EXPLORACIÓN DE DATOS**

In [ ]:

# 1. IMPORTAR LIBRERÍAS

import pandas as pd
import numpy as np




# 2. CARGAR ARCHIVO CSV

ruta_archivo = "Datos Crudos Facebook 10 de Marzo.csv"

df = pd.read_csv(ruta_archivo)

print("Archivo cargado correctamente.")




# 3. DIMENSIONES DEL DATASET

print("Dimensiones del dataset:")
print(df.shape)



# 4. NOMBRES DE COLUMNAS

print("Columnas del dataset:\n")

for i, columna in enumerate(df.columns, start=1):
    print(f"{i}. {columna}")

Archivo cargado correctamente.
Dimensiones del dataset:
(653, 317)
Columnas del dataset:

1. Identificador de la publicación
2. Identificador de la página
3. Nombre de la página
4. Título
5. Descripción
6. Duración (segundos)
7. Hora de publicación
8. Tipo de subtítulo
9. Enlace permanente
10. Es una publicación cruzada
11. Es una publicación compartida
12. Tipo de publicación
13. Idiomas
14. Etiquetas personalizadas
15. Estado de contenido financiado
16. Comentario sobre los datos
17. Fecha
18. Visualizaciones
19. Alcance
20. Reacciones, comentarios y veces que se compartió
21. Reacciones
22. Comentarios
23. Veces que se compartió
24. Total de clics
25. Clics de otro tipo
26. Consumo de segmentación del público coincidente (Photo Click)
27. Ingresos aproximados por monetización de contenido
28. Visualizaciones de Publicaciones orgánicas
29. Visualizaciones de Publicaciones promocionadas
30. Alcance de Publicaciones orgánicas
31. Alcance de Publicaciones promocionadas
32. Reproducciones de video de 3 segundos
33. Reproducciones de video de 1 minuto
34. Espectadores de 3 segundos
35. Espectadores de 1 minuto
36. Reproducciones de video de 3 segundos de Publicaciones promocionadas
37. Reproducciones de video de 3 segundos de Publicaciones orgánicas
38. Reproducciones de video de 1 minuto de Recomendaciones
39. Reproducciones de video de 1 minuto de Contenido compartido
40. Reproducciones de video de 1 minuto de Seguidores
41. Reproducciones de video de 1 minuto de Publicaciones promocionadas
42. Segundos reproducidos en Recomendaciones
43. Segundos reproducidos en Contenido compartido
44. Segundos reproducidos en Seguidores
45. Segundos reproducidos en Publicaciones promocionadas
46. Segundos en promedio producidos en Recomendaciones
47. Segundos en promedio producidos en Contenido compartido
48. Segundos en promedio producidos en Seguidores
49. Segundos en promedio producidos en Publicaciones promocionadas
50. Ingresos por estrellas estimados (USD)
51. Comentarios negativos de los usuarios
52. Comentarios negativos únicos de los usuarios
53. Segundos reproducidos
54. Segundos en promedio reproducidos
55. Porcentaje del total de reproducciones en el intervalo 0
56. Porcentaje del total de reproducciones en el intervalo 1
57. Porcentaje del total de reproducciones en el intervalo 2
58. Porcentaje del total de reproducciones en el intervalo 3
59. Porcentaje del total de reproducciones en el intervalo 4
60. Porcentaje del total de reproducciones en el intervalo 5
61. Porcentaje del total de reproducciones en el intervalo 6
62. Porcentaje del total de reproducciones en el intervalo 7
63. Porcentaje del total de reproducciones en el intervalo 8
64. Porcentaje del total de reproducciones en el intervalo 9
65. Porcentaje del total de reproducciones en el intervalo 10
66. Porcentaje del total de reproducciones en el intervalo 11
67. Porcentaje del total de reproducciones en el intervalo 12
68. Porcentaje del total de reproducciones en el intervalo 13
69. Porcentaje del total de reproducciones en el intervalo 14
70. Porcentaje del total de reproducciones en el intervalo 15
71. Porcentaje del total de reproducciones en el intervalo 16
72. Porcentaje del total de reproducciones en el intervalo 17
73. Porcentaje del total de reproducciones en el intervalo 18
74. Porcentaje del total de reproducciones en el intervalo 19
75. Porcentaje del total de reproducciones en el intervalo 20
76. Porcentaje del total de reproducciones en el intervalo 21
77. Porcentaje del total de reproducciones en el intervalo 22
78. Porcentaje del total de reproducciones en el intervalo 23
79. Porcentaje del total de reproducciones en el intervalo 24
80. Porcentaje del total de reproducciones en el intervalo 25
81. Porcentaje del total de reproducciones en el intervalo 26
82. Porcentaje del total de reproducciones en el intervalo 27
83. Porcentaje del total de reproducciones en el intervalo 28
84. Porcentaje del total de reproducciones en el intervalo 29
85. Porcentaje del total de reproducciones en el intervalo 30
86. Porcentaje del total de reproducciones en el intervalo 31
87. Porcentaje del total de reproducciones en el intervalo 32
88. Porcentaje del total de reproducciones en el intervalo 33
89. Porcentaje del total de reproducciones en el intervalo 34
90. Porcentaje del total de reproducciones en el intervalo 35
91. Porcentaje del total de reproducciones en el intervalo 36
92. Porcentaje del total de reproducciones en el intervalo 37
93. Porcentaje del total de reproducciones en el intervalo 38
94. Porcentaje del total de reproducciones en el intervalo 39
95. Porcentaje del total de reproducciones en el intervalo 40
96. Porcentaje de reproducciones de 15 segundos en el intervalo 0
97. Porcentaje de reproducciones de 15 segundos en el intervalo 1
98. Porcentaje de reproducciones de 15 segundos en el intervalo 2
99. Porcentaje de reproducciones de 15 segundos en el intervalo 3
100. Porcentaje de reproducciones de 15 segundos en el intervalo 4
101. Porcentaje de reproducciones de 15 segundos en el intervalo 5
102. Porcentaje de reproducciones de 15 segundos en el intervalo 6
103. Porcentaje de reproducciones de 15 segundos en el intervalo 7
104. Porcentaje de reproducciones de 15 segundos en el intervalo 8
105. Porcentaje de reproducciones de 15 segundos en el intervalo 9
106. Porcentaje de reproducciones de 15 segundos en el intervalo 10
107. Porcentaje de reproducciones de 15 segundos en el intervalo 11
108. Porcentaje de reproducciones de 15 segundos en el intervalo 12
109. Porcentaje de reproducciones de 15 segundos en el intervalo 13
110. Porcentaje de reproducciones de 15 segundos en el intervalo 14
111. Porcentaje de reproducciones de 15 segundos en el intervalo 15
112. Porcentaje de reproducciones de 15 segundos en el intervalo 16
113. Porcentaje de reproducciones de 15 segundos en el intervalo 17
114. Porcentaje de reproducciones de 15 segundos en el intervalo 18
115. Porcentaje de reproducciones de 15 segundos en el intervalo 19
116. Porcentaje de reproducciones de 15 segundos en el intervalo 20
117. Porcentaje de reproducciones de 15 segundos en el intervalo 21
118. Porcentaje de reproducciones de 15 segundos en el intervalo 22
119. Porcentaje de reproducciones de 15 segundos en el intervalo 23
120. Porcentaje de reproducciones de 15 segundos en el intervalo 24
121. Porcentaje de reproducciones de 15 segundos en el intervalo 25
122. Porcentaje de reproducciones de 15 segundos en el intervalo 26
123. Porcentaje de reproducciones de 15 segundos en el intervalo 27
124. Porcentaje de reproducciones de 15 segundos en el intervalo 28
125. Porcentaje de reproducciones de 15 segundos en el intervalo 29
126. Porcentaje de reproducciones de 15 segundos en el intervalo 30
127. Porcentaje de reproducciones de 15 segundos en el intervalo 31
128. Porcentaje de reproducciones de 15 segundos en el intervalo 32
129. Porcentaje de reproducciones de 15 segundos en el intervalo 33
130. Porcentaje de reproducciones de 15 segundos en el intervalo 34
131. Porcentaje de reproducciones de 15 segundos en el intervalo 35
132. Porcentaje de reproducciones de 15 segundos en el intervalo 36
133. Porcentaje de reproducciones de 15 segundos en el intervalo 37
134. Porcentaje de reproducciones de 15 segundos en el intervalo 38
135. Porcentaje de reproducciones de 15 segundos en el intervalo 39
136. Porcentaje de reproducciones de 15 segundos en el intervalo 40
137. Reproducciones de video de 3 segundos por público destacado (M, 45-54)
138. Reproducciones de video de 3 segundos por público destacado (M, 35-44)
139. Reproducciones de video de 3 segundos por público destacado (F, 35-44)
140. Reproducciones de video de 3 segundos por público destacado (F, 45-54)
141. Reproducciones de video de 3 segundos por público destacado (M, 25-34)
142. Reproducciones de video de 3 segundos por público destacado (F, 25-34)
143. Reproducciones de video de 3 segundos por público destacado (M, 55-64)
144. Reproducciones de video de 3 segundos por público destacado (F, 18-24)
145. Reproducciones de video de 3 segundos por público destacado (F, 55-64)
146. Reproducciones de video de 3 segundos por público destacado (M, 18-24)
147. Reproducciones de video de 3 segundos por público destacado (M, 65+)
148. Reproducciones de video de 3 segundos por público destacado (F, 65+)
149. Reproducciones de video de 3 segundos por país (Mexico (MX))
150. Reproducciones de video de 3 segundos por país (United States (US))
151. Reproducciones de video de 3 segundos por país (Peru (PE))
152. Reproducciones de video de 3 segundos por país (Colombia (CO))
153. Reproducciones de video de 3 segundos por país (Argentina (AR))
154. Reproducciones de video de 3 segundos por país (Spain (ES))
155. Reproducciones de video de 3 segundos por país (Chile (CL))
156. Reproducciones de video de 3 segundos por país (Ecuador (EC))
157. Reproducciones de video de 3 segundos por país (Bolivia (BO))
158. Reproducciones de video de 3 segundos por país (Guatemala (GT))
159. Reproducciones de video de 3 segundos por país (Brazil (BR))
160. Reproducciones de video de 3 segundos por país (Kenya (KE))
161. Reproducciones de video de 3 segundos por país (Poland (PL))
162. Reproducciones de video de 3 segundos por país (Germany (DE))
163. Reproducciones de video de 3 segundos por país (Honduras (HN))
164. Reproducciones de video de 3 segundos por país (Dominican Republic (DO))
165. Reproducciones de video de 3 segundos por país (Bermuda (BM))
166. Reproducciones de video de 3 segundos por país (Costa Rica (CR))
167. Reproducciones de video de 3 segundos por país (El Salvador (SV))
168. Reproducciones de video de 3 segundos por país (Philippines (PH))
169. Reproducciones de video de 3 segundos por país (Venezuela (VE))
170. Reproducciones de video de 3 segundos por país (Sweden (SE))
171. Reproducciones de video de 3 segundos por país (Puerto Rico (PR))
172. Reproducciones de video de 3 segundos por país (Indonesia (ID))
173. Reproducciones de video de 3 segundos por país (Japan (JP))
174. Reproducciones de video de 3 segundos por país (United Kingdom (GB))
175. Reproducciones de video de 3 segundos por país (France (FR))
176. Reproducciones de video de 3 segundos por país (Uruguay (UY))
177. Reproducciones de video de 3 segundos por país (Nicaragua (NI))
178. Reproducciones de video de 3 segundos por país (Italy (IT))
179. Reproducciones de video de 3 segundos por país (Canada (CA))
180. Reproducciones de video de 3 segundos por país (Pakistan (PK))
181. Reproducciones de video de 3 segundos por país (Singapore (SG))
182. Reproducciones de video de 3 segundos por país (Nigeria (NG))
183. Reproducciones de video de 3 segundos por país (Switzerland (CH))
184. Reproducciones de video de 3 segundos por país (Czech Republic (CZ))
185. Reproducciones de video de 3 segundos por país (Madagascar (MG))
186. Reproducciones de video de 3 segundos por país (Romania (RO))
187. Reproducciones de video de 3 segundos por país (Barbados (BB))
188. Reproducciones de video de 3 segundos por país (Trinidad and Tobago (TT))
189. Reproducciones de video de 3 segundos por país (Hungary (HU))
190. Reproducciones de video de 3 segundos por país (Australia (AU))
191. Reproducciones de video de 3 segundos por país (Ukraine (UA))
192. Reproducciones de video de 3 segundos por país (Norway (NO))
193. Reproducciones de video de 3 segundos por país (India (IN))
194. Reproducciones de video de 3 segundos por país (Netherlands (NL))
195. Reproducciones de video de 3 segundos por país (Belgium (BE))
196. Reproducciones de video de 3 segundos por país (Panama (PA))
197. Reproducciones de video de 3 segundos por país (Thailand (TH))
198. Reproducciones de video de 3 segundos por país (Paraguay (PY))
199. Reproducciones de video de 3 segundos por país (New Zealand (NZ))
200. Reproducciones de video de 3 segundos por país (Greece (GR))
201. Reproducciones de video de 3 segundos por país (Austria (AT))
202. Reproducciones de video de 3 segundos por país (Portugal (PT))
203. Reproducciones de video de 3 segundos por país (Malaysia (MY))
204. Reproducciones de video de 3 segundos por país (Sierra Leone (SL))
205. Reproducciones de video de 3 segundos por país (Mauritius (MU))
206. Reproducciones de video de 3 segundos por país (Montenegro (ME))
207. Reproducciones de video de 3 segundos por país (South Africa (ZA))
208. Espectadores recurrentes
209. Reproducciones de video de 1 minuto de espectadores recurrentes
210. Segundos reproducidos por espectadores recurrentes
211. Segundos en promedio reproducidos por espectadores recurrentes
212. Clics en el enlace
213. Reproducciones de video de 3 segundos por país (Turkey (TR))
214. Reproducciones de video de 3 segundos por país (Ireland (IE))
215. Reproducciones de video de 3 segundos por país (Cambodia (KH))
216. Reproducciones de video de 3 segundos por país (Myanmar (MM))
217. Reproducciones de video de 3 segundos por país (Belize (BZ))
218. Reproducciones de video de 3 segundos por país (South Korea (KR))
219. Reproducciones de video de 3 segundos por país (Lithuania (LT))
220. Reproducciones de video de 3 segundos por país (Mozambique (MZ))
221. Reproducciones de video de 3 segundos por país (Central African Republic (CF))
222. Reproducciones de video de 3 segundos por país (Slovakia (SK))
223. Reproducciones de video de 3 segundos por país (Vietnam (VN))
224. Reproducciones de video de 3 segundos por país (China (CN))
225. Reproducciones de video de 3 segundos por país (Iraq (IQ))
226. Reproducciones de video de 3 segundos por país (Croatia (HR))
227. Reproducciones de video de 3 segundos por país (Cuba (CU))
228. Reproducciones de video de 3 segundos por país (Kosovo (XK))
229. Reproducciones de video de 3 segundos por país (United Arab Emirates (AE))
230. Reproducciones de video de 3 segundos por país (The Bahamas (BS))
231. Reproducciones de video de 3 segundos por país (Bangladesh (BD))
232. Reproducciones de video de 3 segundos por país (Moldova (MD))
233. Reproducciones de video de 3 segundos por país (Algeria (DZ))
234. Reproducciones de video de 3 segundos por país (Ghana (GH))
235. Reproducciones de video de 3 segundos por país (Bulgaria (BG))
236. Reproducciones de video de 3 segundos por país (Finland (FI))
237. Reproducciones de video de 3 segundos por país (Denmark (DK))
238. Reproducciones de video de 3 segundos por país (Belarus (BY))
239. Reproducciones de video de 3 segundos por país (Slovenia (SI))
240. Reproducciones de video de 3 segundos por país (Hong Kong (HK))
241. Reproducciones de video de 3 segundos por país (Morocco (MA))
242. Reproducciones de video de 3 segundos por país (Israel (IL))
243. Reproducciones de video de 3 segundos por país (Guyana (GY))
244. Reproducciones de video de 3 segundos por país (Senegal (SN))
245. Reproducciones de video de 3 segundos por país (Latvia (LV))
246. Reproducciones de video de 3 segundos por país (Estonia (EE))
247. Reproducciones de video de 3 segundos por país (Niger (NE))
248. Reproducciones de video de 3 segundos por país (Serbia (RS))
249. Reproducciones de video de 3 segundos por país (Sri Lanka (LK))
250. Reproducciones de video de 3 segundos por país (Zambia (ZM))
251. Ingresos estimados (USD)
252. Reproducciones de video de 3 segundos por país (Andorra (AD))
253. Reproducciones de video de 3 segundos por país (Iceland (IS))
254. Reproducciones de video de 3 segundos por país (Yemen (YE))
255. Reproducciones de video de 3 segundos por país (North Macedonia (MK))
256. Reproducciones de video de 3 segundos por país (Egypt (EG))
257. Reproducciones de video de 3 segundos por país (Kazakhstan (KZ))
258. Reproducciones de video de 3 segundos por país (Taiwan (TW))
259. Reproducciones de video de 3 segundos por país (Aruba (AW))
260. Reproducciones de video de 3 segundos por país (Luxembourg (LU))
261. Reproducciones de video de 3 segundos por país (Syria (SY))
262. Reproducciones de video de 3 segundos por país (Ethiopia (ET))
263. Reproducciones de video de 3 segundos por país (Jamaica (JM))
264. Reproducciones de video de 3 segundos por país (Guernsey (GG))
265. Reproducciones de video de 3 segundos por país (Oman (OM))
266. Reproducciones de video de 3 segundos por país (Turks and Caicos Islands (TC))
267. Reproducciones de video de 3 segundos por país (Haiti (HT))
268. Reproducciones de video de 3 segundos por país (Armenia (AM))
269. Reproducciones de video de 3 segundos por país (Jordan (JO))
270. Reproducciones de video de 3 segundos por país (Saudi Arabia (SA))
271. Reproducciones de video de 3 segundos por país (Bosnia and Herzegovina (BA))
272. Reproducciones de video de 3 segundos por país (Tunisia (TN))
273. Reproducciones de video de 3 segundos por país (Tajikistan (TJ))
274. Reproducciones de video de 3 segundos por país (Nepal (NP))
275. Reproducciones de video de 3 segundos por país (Martinique (MQ))
276. Reproducciones de video de 3 segundos por país (Georgia (GE))
277. Reproducciones de video de 3 segundos por país (Brunei (BN))
278. Reproducciones de video de 3 segundos por país (Malawi (MW))
279. Reproducciones de video de 3 segundos por país (Sint Maarten (SX))
280. Comentarios negativos de los usuarios: Ocultar todo
281. Comentarios negativos únicos de los usuarios: Ocultar todo
282. Reproducciones de video de 3 segundos por país (Burkina Faso (BF))
283. Reproducciones de video de 3 segundos por país (Mayotte (YT))
284. Reproducciones de video de 3 segundos por país (Equatorial Guinea (GQ))
285. Reproducciones de video de 3 segundos por país (Côte d'Ivoire (CI))
286. Reproducciones de video de 3 segundos por país (Russia (RU))
287. Reproducciones de video de 3 segundos por país (Lebanon (LB))
288. Reproducciones de video de 3 segundos por país (Palestine (PS))
289. Reproducciones de video de 3 segundos por país (Libya (LY))
290. Reproducciones de video de 3 segundos por país (Bahrain (BH))
291. Reproducciones de video de 3 segundos por país (Kuwait (KW))
292. Reproducciones de video de 3 segundos por país (Suriname (SR))
293. Reproducciones de video de 3 segundos por país (Afghanistan (AF))
294. Reproducciones de video de 3 segundos por país (Sudan (SD))
295. Reproducciones de video de 3 segundos por país (Uganda (UG))
296. Reproducciones de video de 3 segundos por país (Botswana (BW))
297. Reproducciones de video de 3 segundos por país (Mongolia (MN))
298. Reproducciones de video de 3 segundos por país (French Guiana (GF))
299. Reproducciones de video de 3 segundos por país (Macau (MO))
300. Reproducciones de video de 3 segundos por país (Iran (IR))
301. Reproducciones de video de 3 segundos por país (Uzbekistan (UZ))
302. Reproducciones de video de 3 segundos por país (Malta (MT))
303. Reproducciones de video de 3 segundos por país (Kyrgyzstan (KG))
304. Reproducciones de video de 3 segundos por país (Jersey (JE))
305. Reproducciones de video de 3 segundos por país (Chad (TD))
306. Comentarios negativos de los usuarios: Ocultar
307. Comentarios negativos únicos de los usuarios: Ocultar
308. Reproducciones de video de 3 segundos por país (Réunion (RE))
309. Reproducciones de video de 3 segundos por país (Guam (GU))
310. Reproducciones de video de 3 segundos por país (Cayman Islands (KY))
311. Reproducciones de video de 3 segundos por país (Albania (AL))
312. Reproducciones de video de 3 segundos por país (Tanzania (TZ))
313. Reproducciones de video de 3 segundos por país (Burundi (BI))
314. Reproducciones de video de 3 segundos por país (Fiji (FJ))
315. Reproducciones de video de 3 segundos por país (Bonaire, Sint Eustatius and Saba (BQ))
316. Reproducciones de video de 3 segundos por país (Papua New Guinea (PG))
317. Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))

In [ ]:

# 5. INFORMACIÓN GENERAL DEL DATASET

print("Información general:\n")

df.info()



# 6. PRIMERAS FILAS DEL DATASET

print("Primeras filas:\n")

display(df.head())



# 7. VALORES NULOS POR COLUMNA

nulos = df.isnull().sum().sort_values(ascending=False)

print("Valores nulos por columna:\n")

display(nulos)




# 8. PORCENTAJE DE VALORES NULOS

porcentaje_nulos = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

print("Porcentaje de valores nulos:\n")

display(porcentaje_nulos)

Información general:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Columns: 317 entries, Identificador de la publicación to Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))
dtypes: float64(290), int64(19), object(8)
memory usage: 1.6+ MB
Primeras filas:

,Identificador de la publicación,Identificador de la página,Nombre de la página,Título,Descripción,Duración (segundos),Hora de publicación,Tipo de subtítulo,Enlace permanente,Es una publicación cruzada,...,Reproducciones de video de 3 segundos por país (Réunion (RE)),Reproducciones de video de 3 segundos por país (Guam (GU)),Reproducciones de video de 3 segundos por país (Cayman Islands (KY)),Reproducciones de video de 3 segundos por país (Albania (AL)),Reproducciones de video de 3 segundos por país (Tanzania (TZ)),Reproducciones de video de 3 segundos por país (Burundi (BI)),Reproducciones de video de 3 segundos por país (Fiji (FJ)),"Reproducciones de video de 3 segundos por país (Bonaire, Sint Eustatius and Saba (BQ))",Reproducciones de video de 3 segundos por país (Papua New Guinea (PG)),Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))
0,1430953675493171,100057356563301,Sonido Los Puercos del Rock,¡Los Puercos Del Rock desde Frontón el Puente!...,¡Los Puercos Del Rock desde Frontón el Puente!...,20,01/15/2026 17:59,NaN,https://www.facebook.com/reel/1672479884135964/,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1431073182147887,100057356563301,Sonido Los Puercos del Rock,Los esperamos! 😎✌🏽,NaN,0,01/15/2026 21:21,NaN,https://www.facebook.com/permalink.php?story_f...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1431088425479696,100057356563301,Sonido Los Puercos del Rock,Épaleeee! ✌🏽🐽,NaN,0,01/15/2026 21:47,NaN,https://www.facebook.com/permalink.php?story_f...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1431516552103550,100057356563301,Sonido Los Puercos del Rock,✌🏽🐽,NaN,0,01/16/2026 09:47,NaN,https://www.facebook.com/permalink.php?story_f...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1431547902100415,100057356563301,Sonido Los Puercos del Rock,Oink toca 🤘🏽🐽🎸\n\n#rocknroll #rock #rockandrol...,NaN,0,01/16/2026 10:43,NaN,https://www.facebook.com/permalink.php?story_f...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Valores nulos por columna:

Idiomas                                                                 653
Etiquetas personalizadas                                                653
Comentario sobre los datos                                              653
Estado de contenido financiado                                          653
Reproducciones de video de 3 segundos por país (Uganda (UG))            652
                                                                       ...
Alcance de Publicaciones promocionadas                                    0
Reproducciones de video de 3 segundos                                     0
Reproducciones de video de 3 segundos de Publicaciones promocionadas      0
Reproducciones de video de 3 segundos de Publicaciones orgánicas          0
Identificador de la publicación                                           0
Length: 317, dtype: int64

Porcentaje de valores nulos:

Idiomas                                                                 100.000000
Etiquetas personalizadas                                                100.000000
Comentario sobre los datos                                              100.000000
Estado de contenido financiado                                          100.000000
Reproducciones de video de 3 segundos por país (Uganda (UG))             99.846861
                                                                           ...
Alcance de Publicaciones promocionadas                                    0.000000
Reproducciones de video de 3 segundos                                     0.000000
Reproducciones de video de 3 segundos de Publicaciones promocionadas      0.000000
Reproducciones de video de 3 segundos de Publicaciones orgánicas          0.000000
Identificador de la publicación                                           0.000000
Length: 317, dtype: float64

In [ ]:

# 9. CANTIDAD DE CEROS POR COLUMNA

ceros = (
    (df == 0)
    .sum(numeric_only=True)
    .sort_values(ascending=False)
)

print("Cantidad de ceros por columna:\n")

display(ceros)




# 10. PORCENTAJE DE CEROS POR COLUMNA

porcentaje_ceros = (
    (df == 0)
    .mean(numeric_only=True) * 100
).sort_values(ascending=False)

print("Porcentaje de ceros por columna:\n")

display(porcentaje_ceros)




# 11. VALORES ÚNICOS POR COLUMNA

valores_unicos = (
    df.nunique()
    .sort_values()
)

print("Cantidad de valores únicos por columna:\n")

display(valores_unicos)



# 12. ESTADÍSTICAS DESCRIPTIVAS

print("Estadísticas descriptivas:\n")

display(df.describe())

Cantidad de ceros por columna:

Visualizaciones de Publicaciones promocionadas                                     653
Reproducciones de video de 3 segundos de Publicaciones promocionadas               653
Alcance de Publicaciones promocionadas                                             653
Ingresos por estrellas estimados (USD)                                             650
Es una publicación cruzada                                                         645
                                                                                  ...
Reproducciones de video de 3 segundos por país (Sweden (SE))                         0
Reproducciones de video de 3 segundos por país (Puerto Rico (PR))                    0
Reproducciones de video de 3 segundos por país (Indonesia (ID))                      0
Reproducciones de video de 3 segundos por país (Japan (JP))                          0
Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))      0
Length: 317, dtype: int64

Porcentaje de ceros por columna:

Visualizaciones de Publicaciones promocionadas                                     100.000000
Reproducciones de video de 3 segundos de Publicaciones promocionadas               100.000000
Alcance de Publicaciones promocionadas                                             100.000000
Ingresos por estrellas estimados (USD)                                              99.540582
Es una publicación cruzada                                                          98.774885
                                                                                      ...
Reproducciones de video de 3 segundos por país (Sweden (SE))                         0.000000
Reproducciones de video de 3 segundos por país (Puerto Rico (PR))                    0.000000
Reproducciones de video de 3 segundos por país (Indonesia (ID))                      0.000000
Reproducciones de video de 3 segundos por país (Japan (JP))                          0.000000
Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))      0.000000
Length: 317, dtype: float64

Cantidad de valores únicos por columna:

Comentario sobre los datos                                                           0
Estado de contenido financiado                                                       0
Etiquetas personalizadas                                                             0
Idiomas                                                                              0
Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))      1
                                                                                  ...
Alcance                                                                            622
Visualizaciones de Publicaciones orgánicas                                         647
Visualizaciones                                                                    647
Enlace permanente                                                                  653
Identificador de la publicación                                                    653
Length: 317, dtype: int64

Estadísticas descriptivas:

,Identificador de la publicación,Identificador de la página,Duración (segundos),Es una publicación cruzada,Es una publicación compartida,Idiomas,Etiquetas personalizadas,Estado de contenido financiado,Comentario sobre los datos,Visualizaciones,...,Reproducciones de video de 3 segundos por país (Réunion (RE)),Reproducciones de video de 3 segundos por país (Guam (GU)),Reproducciones de video de 3 segundos por país (Cayman Islands (KY)),Reproducciones de video de 3 segundos por país (Albania (AL)),Reproducciones de video de 3 segundos por país (Tanzania (TZ)),Reproducciones de video de 3 segundos por país (Burundi (BI)),Reproducciones de video de 3 segundos por país (Fiji (FJ)),"Reproducciones de video de 3 segundos por país (Bonaire, Sint Eustatius and Saba (BQ))",Reproducciones de video de 3 segundos por país (Papua New Guinea (PG)),Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))
count,6.530000e+02,6.530000e+02,653.000000,653.000000,653.000000,0.0,0.0,0.0,0.0,6.520000e+02,...,4.0,3.0,7.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,1.344544e+15,1.000574e+14,56.298622,0.012251,0.252680,NaN,NaN,NaN,NaN,4.188863e+04,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
std,1.181729e+14,0.000000e+00,207.429982,0.110089,0.434882,NaN,NaN,NaN,NaN,2.392660e+05,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,7.584057e+14,1.000574e+14,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,1.000000e+00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
25%,1.268052e+15,1.000574e+14,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,3.827500e+03,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
50%,1.358552e+15,1.000574e+14,11.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,8.896500e+03,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
75%,1.418910e+15,1.000574e+14,60.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,2.032500e+04,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
max,2.771238e+15,1.000574e+14,2907.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,4.205501e+06,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:

# 13. DETECTAR FILAS DUPLICADAS

duplicados = df.duplicated().sum()

print(f"Cantidad de filas duplicadas: {duplicados}")




# 14. BUSCAR COLUMNAS RELACIONADAS CON PAÍSES

columnas_paises = [
    col for col in df.columns
    if "país" in col.lower()
]

print("Columnas relacionadas con países:\n")

for col in columnas_paises:
    print(col)




# 15. BUSCAR COLUMNAS RELACIONADAS CON VIDEOS

columnas_video = [
    col for col in df.columns
    if "video" in col.lower()
]

print("Columnas relacionadas con video:\n")

for col in columnas_video:
    print(col)




# 16. BUSCAR COLUMNAS RELACIONADAS CON REACCIONES

columnas_reacciones = [
    col for col in df.columns
    if "reacción" in col.lower()
    or "like" in col.lower()
    or "coment" in col.lower()
    or "compart" in col.lower()
]

print("Columnas relacionadas con interacción:\n")

for col in columnas_reacciones:
    print(col)

Cantidad de filas duplicadas: 0
Columnas relacionadas con países:

Reproducciones de video de 3 segundos por país (Mexico (MX))
Reproducciones de video de 3 segundos por país (United States (US))
Reproducciones de video de 3 segundos por país (Peru (PE))
Reproducciones de video de 3 segundos por país (Colombia (CO))
Reproducciones de video de 3 segundos por país (Argentina (AR))
Reproducciones de video de 3 segundos por país (Spain (ES))
Reproducciones de video de 3 segundos por país (Chile (CL))
Reproducciones de video de 3 segundos por país (Ecuador (EC))
Reproducciones de video de 3 segundos por país (Bolivia (BO))
Reproducciones de video de 3 segundos por país (Guatemala (GT))
Reproducciones de video de 3 segundos por país (Brazil (BR))
Reproducciones de video de 3 segundos por país (Kenya (KE))
Reproducciones de video de 3 segundos por país (Poland (PL))
Reproducciones de video de 3 segundos por país (Germany (DE))
Reproducciones de video de 3 segundos por país (Honduras (HN))
Reproducciones de video de 3 segundos por país (Dominican Republic (DO))
Reproducciones de video de 3 segundos por país (Bermuda (BM))
Reproducciones de video de 3 segundos por país (Costa Rica (CR))
Reproducciones de video de 3 segundos por país (El Salvador (SV))
Reproducciones de video de 3 segundos por país (Philippines (PH))
Reproducciones de video de 3 segundos por país (Venezuela (VE))
Reproducciones de video de 3 segundos por país (Sweden (SE))
Reproducciones de video de 3 segundos por país (Puerto Rico (PR))
Reproducciones de video de 3 segundos por país (Indonesia (ID))
Reproducciones de video de 3 segundos por país (Japan (JP))
Reproducciones de video de 3 segundos por país (United Kingdom (GB))
Reproducciones de video de 3 segundos por país (France (FR))
Reproducciones de video de 3 segundos por país (Uruguay (UY))
Reproducciones de video de 3 segundos por país (Nicaragua (NI))
Reproducciones de video de 3 segundos por país (Italy (IT))
Reproducciones de video de 3 segundos por país (Canada (CA))
Reproducciones de video de 3 segundos por país (Pakistan (PK))
Reproducciones de video de 3 segundos por país (Singapore (SG))
Reproducciones de video de 3 segundos por país (Nigeria (NG))
Reproducciones de video de 3 segundos por país (Switzerland (CH))
Reproducciones de video de 3 segundos por país (Czech Republic (CZ))
Reproducciones de video de 3 segundos por país (Madagascar (MG))
Reproducciones de video de 3 segundos por país (Romania (RO))
Reproducciones de video de 3 segundos por país (Barbados (BB))
Reproducciones de video de 3 segundos por país (Trinidad and Tobago (TT))
Reproducciones de video de 3 segundos por país (Hungary (HU))
Reproducciones de video de 3 segundos por país (Australia (AU))
Reproducciones de video de 3 segundos por país (Ukraine (UA))
Reproducciones de video de 3 segundos por país (Norway (NO))
Reproducciones de video de 3 segundos por país (India (IN))
Reproducciones de video de 3 segundos por país (Netherlands (NL))
Reproducciones de video de 3 segundos por país (Belgium (BE))
Reproducciones de video de 3 segundos por país (Panama (PA))
Reproducciones de video de 3 segundos por país (Thailand (TH))
Reproducciones de video de 3 segundos por país (Paraguay (PY))
Reproducciones de video de 3 segundos por país (New Zealand (NZ))
Reproducciones de video de 3 segundos por país (Greece (GR))
Reproducciones de video de 3 segundos por país (Austria (AT))
Reproducciones de video de 3 segundos por país (Portugal (PT))
Reproducciones de video de 3 segundos por país (Malaysia (MY))
Reproducciones de video de 3 segundos por país (Sierra Leone (SL))
Reproducciones de video de 3 segundos por país (Mauritius (MU))
Reproducciones de video de 3 segundos por país (Montenegro (ME))
Reproducciones de video de 3 segundos por país (South Africa (ZA))
Reproducciones de video de 3 segundos por país (Turkey (TR))
Reproducciones de video de 3 segundos por país (Ireland (IE))
Reproducciones de video de 3 segundos por país (Cambodia (KH))
Reproducciones de video de 3 segundos por país (Myanmar (MM))
Reproducciones de video de 3 segundos por país (Belize (BZ))
Reproducciones de video de 3 segundos por país (South Korea (KR))
Reproducciones de video de 3 segundos por país (Lithuania (LT))
Reproducciones de video de 3 segundos por país (Mozambique (MZ))
Reproducciones de video de 3 segundos por país (Central African Republic (CF))
Reproducciones de video de 3 segundos por país (Slovakia (SK))
Reproducciones de video de 3 segundos por país (Vietnam (VN))
Reproducciones de video de 3 segundos por país (China (CN))
Reproducciones de video de 3 segundos por país (Iraq (IQ))
Reproducciones de video de 3 segundos por país (Croatia (HR))
Reproducciones de video de 3 segundos por país (Cuba (CU))
Reproducciones de video de 3 segundos por país (Kosovo (XK))
Reproducciones de video de 3 segundos por país (United Arab Emirates (AE))
Reproducciones de video de 3 segundos por país (The Bahamas (BS))
Reproducciones de video de 3 segundos por país (Bangladesh (BD))
Reproducciones de video de 3 segundos por país (Moldova (MD))
Reproducciones de video de 3 segundos por país (Algeria (DZ))
Reproducciones de video de 3 segundos por país (Ghana (GH))
Reproducciones de video de 3 segundos por país (Bulgaria (BG))
Reproducciones de video de 3 segundos por país (Finland (FI))
Reproducciones de video de 3 segundos por país (Denmark (DK))
Reproducciones de video de 3 segundos por país (Belarus (BY))
Reproducciones de video de 3 segundos por país (Slovenia (SI))
Reproducciones de video de 3 segundos por país (Hong Kong (HK))
Reproducciones de video de 3 segundos por país (Morocco (MA))
Reproducciones de video de 3 segundos por país (Israel (IL))
Reproducciones de video de 3 segundos por país (Guyana (GY))
Reproducciones de video de 3 segundos por país (Senegal (SN))
Reproducciones de video de 3 segundos por país (Latvia (LV))
Reproducciones de video de 3 segundos por país (Estonia (EE))
Reproducciones de video de 3 segundos por país (Niger (NE))
Reproducciones de video de 3 segundos por país (Serbia (RS))
Reproducciones de video de 3 segundos por país (Sri Lanka (LK))
Reproducciones de video de 3 segundos por país (Zambia (ZM))
Reproducciones de video de 3 segundos por país (Andorra (AD))
Reproducciones de video de 3 segundos por país (Iceland (IS))
Reproducciones de video de 3 segundos por país (Yemen (YE))
Reproducciones de video de 3 segundos por país (North Macedonia (MK))
Reproducciones de video de 3 segundos por país (Egypt (EG))
Reproducciones de video de 3 segundos por país (Kazakhstan (KZ))
Reproducciones de video de 3 segundos por país (Taiwan (TW))
Reproducciones de video de 3 segundos por país (Aruba (AW))
Reproducciones de video de 3 segundos por país (Luxembourg (LU))
Reproducciones de video de 3 segundos por país (Syria (SY))
Reproducciones de video de 3 segundos por país (Ethiopia (ET))
Reproducciones de video de 3 segundos por país (Jamaica (JM))
Reproducciones de video de 3 segundos por país (Guernsey (GG))
Reproducciones de video de 3 segundos por país (Oman (OM))
Reproducciones de video de 3 segundos por país (Turks and Caicos Islands (TC))
Reproducciones de video de 3 segundos por país (Haiti (HT))
Reproducciones de video de 3 segundos por país (Armenia (AM))
Reproducciones de video de 3 segundos por país (Jordan (JO))
Reproducciones de video de 3 segundos por país (Saudi Arabia (SA))
Reproducciones de video de 3 segundos por país (Bosnia and Herzegovina (BA))
Reproducciones de video de 3 segundos por país (Tunisia (TN))
Reproducciones de video de 3 segundos por país (Tajikistan (TJ))
Reproducciones de video de 3 segundos por país (Nepal (NP))
Reproducciones de video de 3 segundos por país (Martinique (MQ))
Reproducciones de video de 3 segundos por país (Georgia (GE))
Reproducciones de video de 3 segundos por país (Brunei (BN))
Reproducciones de video de 3 segundos por país (Malawi (MW))
Reproducciones de video de 3 segundos por país (Sint Maarten (SX))
Reproducciones de video de 3 segundos por país (Burkina Faso (BF))
Reproducciones de video de 3 segundos por país (Mayotte (YT))
Reproducciones de video de 3 segundos por país (Equatorial Guinea (GQ))
Reproducciones de video de 3 segundos por país (Côte d'Ivoire (CI))
Reproducciones de video de 3 segundos por país (Russia (RU))
Reproducciones de video de 3 segundos por país (Lebanon (LB))
Reproducciones de video de 3 segundos por país (Palestine (PS))
Reproducciones de video de 3 segundos por país (Libya (LY))
Reproducciones de video de 3 segundos por país (Bahrain (BH))
Reproducciones de video de 3 segundos por país (Kuwait (KW))
Reproducciones de video de 3 segundos por país (Suriname (SR))
Reproducciones de video de 3 segundos por país (Afghanistan (AF))
Reproducciones de video de 3 segundos por país (Sudan (SD))
Reproducciones de video de 3 segundos por país (Uganda (UG))
Reproducciones de video de 3 segundos por país (Botswana (BW))
Reproducciones de video de 3 segundos por país (Mongolia (MN))
Reproducciones de video de 3 segundos por país (French Guiana (GF))
Reproducciones de video de 3 segundos por país (Macau (MO))
Reproducciones de video de 3 segundos por país (Iran (IR))
Reproducciones de video de 3 segundos por país (Uzbekistan (UZ))
Reproducciones de video de 3 segundos por país (Malta (MT))
Reproducciones de video de 3 segundos por país (Kyrgyzstan (KG))
Reproducciones de video de 3 segundos por país (Jersey (JE))
Reproducciones de video de 3 segundos por país (Chad (TD))
Reproducciones de video de 3 segundos por país (Réunion (RE))
Reproducciones de video de 3 segundos por país (Guam (GU))
Reproducciones de video de 3 segundos por país (Cayman Islands (KY))
Reproducciones de video de 3 segundos por país (Albania (AL))
Reproducciones de video de 3 segundos por país (Tanzania (TZ))
Reproducciones de video de 3 segundos por país (Burundi (BI))
Reproducciones de video de 3 segundos por país (Fiji (FJ))
Reproducciones de video de 3 segundos por país (Bonaire, Sint Eustatius and Saba (BQ))
Reproducciones de video de 3 segundos por país (Papua New Guinea (PG))
Reproducciones de video de 3 segundos por país (Saint Pierre and Miquelon (PM))
Columnas relacionadas con video:

Reproducciones de video de 3 segundos
Reproducciones de video de 1 minuto
Reproducciones de video de 3 segundos de Publicaciones promocionadas
Reproducciones de video de 3 segundos de Publicaciones orgánicas
Reproducciones de video de 1 minuto de Recomendaciones
Reproducciones de video de 1 minuto de Contenido compartido
Reproducciones de video de 1 minuto de Seguidores
Reproducciones de video de 1 minuto de Publicaciones promocionadas
Reproducciones de video de 3 segundos por público destacado (M, 45-54)
Reproducciones de video de 3 segundos por público destacado (M, 35-44)
Reproducciones de video de 3 segundos por público destacado (F, 35-44)
Reproducciones de video de 3 segundos por público destacado (F, 45-54)
Reproducciones de video de 3 segundos por público destacado (M, 25-34)
Reproducciones de video de 3 segundos por público destacado (F, 25-34)
Reproducciones de video de 3 segundos por público destacado (M, 55-64)
Reproducciones de video de 3 segundos por público destacado (F, 18-24)
Reproducciones de video de 3 segundos por público destacado (F, 55-64)
Reproducciones de video de 3 segundos por público destacado (M, 18-24)
Reproducciones de video de 3 segundos por público destacado (M, 65+)
Reproducciones de video de 3 segundos por público destacado (F, 65+)
Reproducciones de video de 3 segundos por país (Mexico (MX))
Reproducciones de video de 3 segundos por país (United States (US))
Reproducciones de video de 3 segundos por país (Peru (PE))
Reproducciones de video de 3 segundos por país (Colombia (CO))
Reproducciones de video de 3 segundos por país (Argentina (AR))
Reproducciones de video de 3 segundos por país (Spain (ES))
Reproducciones de video de 3 segundos por país (Chile (CL))
Reproducciones de video de 3 segundos por país (Ecuador (EC))
Reproducciones de video de 3 segundos por país (Bolivia (BO))
Reproducciones de video de 3 segundos por país (Guatemala (GT))
Reproducciones de video de 3 segundos por país (Brazil (BR))
Reproducciones de video de 3 segundos por país (Kenya (KE))
Reproducciones de video de 3 segundos por país (Poland (PL))
Reproducciones de video de 3 segundos por país (Germany (DE))
Reproducciones de video de 3 segundos por país (Honduras (HN))
Reproducciones de video de 3 segundos por país (Dominican Republic (DO))
Reproducciones de video de 3 segundos por país (Bermuda (BM))
Reproducciones de video de 3 segundos por país (Costa Rica (CR))
Reproducciones de video de 3 segundos por país (El Salvador (SV))
Reproducciones de video de 3 segundos por país (Philippines (PH))
Reproducciones de video de 3 segundos por país (Venezuela (VE))
Reproducciones de video de 3 segundos por país (Sweden (SE))
Reproducciones de video de 3 segundos por país (Puerto Rico (PR))
Reproducciones de video de 3 segundos por país (Indonesia (ID))
Reproducciones de video de 3 segundos por país (Japan (JP))
Reproducciones de video de 3 segundos por país (United Kingdom (GB))
Reproducciones de video de 3 segundos por país (France (FR))
Reproducciones de video de 3 segundos por país (Uruguay (UY))
Reproducciones de video de 3 segundos por país (Nicaragua (NI))
Reproducciones de video de 3 segundos por país (Italy (IT))
Reproducciones de video de 3 segundos por país (Canada (CA))
Reproducciones de video de 3 segundos por país (Pakistan (PK))
Reproducciones de video de 3 segundos por país (Singapore (SG))
Reproducciones de video de 3 segundos por país (Nigeria (NG))
Reproducciones de video de 3 segundos por país (Switzerland (CH))
Reproducciones de video de 3 segundos por país (Czech Republic (CZ))
Reproducciones de video de 3 segundos por país (Madagascar (MG))
Reproducciones de video de 3 segundos por país (Romania (RO))
Reproducciones de video de 3 segundos por país (Barbados (BB))
Reproducciones de video de 3 segundos por país (Trinidad and Tobago (TT))
Reproducciones de video de 3 segundos por país (Hungary (HU))
Reproducciones de video de 3 segundos por país (Australia (AU))
Reproducciones de video de 3 segundos por país (Ukraine (UA))
Reproducciones de video de 3 segundos por país (Norway (NO))
Reproducciones de video de 3 segundos por país (India (IN))
Reproducciones de video de 3 segundos por país (Netherlands (NL))
Reproducciones de video de 3 segundos por país (Belgium (BE))
Reproducciones de video de 3 segundos por país (Panama (PA))
Reproducciones de video de 3 segundos por país (Thailand (TH))
Reproducciones de video de 3 segundos por país (Paraguay (PY))
Reproducciones de video de 3 segundos por país (New Zealand (NZ))
Reproducciones de video de 3 segundos por país (Greece (GR))
Reproducciones de video de 3 segundos por país (Austria (AT))
Reproducciones de video de 3 segundos por país (Portugal (PT))
Reproducciones de video de 3 segundos por país (Malaysia (MY))
Reproducciones de video de 3 segundos por país (Sierra Leone (SL))
Reproducciones de video de 3 segundos por país (Mauritius (MU))
Reproducciones de video de 3 segundos por país (Montenegro (ME))
Reproducciones de video de 3 segundos por país (South Africa (ZA))
Reproducciones de video de 1 minuto de espectadores recurrentes
Reproducciones de video de 3 segundos por país (Turkey (TR))
Reproducciones de video de 3 segundos por país (Ireland (IE))
Reproducciones de video de 3 segundos por país (Cambodia (KH))
Reproducciones de video de 3 segundos por país (Myanmar (MM))
Reproducciones de video de 3 segundos por país (Belize (BZ))
Reproducciones de video de 3 segundos por país (South Korea (KR))
Reproducciones de video de 3 segundos por país (Lithuania (LT))
Reproducciones de video de 3 segundos por país (Mozambique (MZ))
Reproducciones de video de 3 segundos por país (Central African Republic (CF))
Reproducciones de video de 3 segundos por país (Slovakia (SK))
Reproducciones de video de 3 segundos por país (Vietnam (VN))
Reproducciones de video de 3 segundos por país (China (CN))
Reproducciones de video de 3 segundos por país (Iraq (IQ))
Reproducciones de video de 3 segundos por país (Croatia (HR))
Reproducciones de video de 3 segundos por país (Cuba (CU))
Reproducciones de video de 3 segundos por país (Kosovo (XK))
Reproducciones de video de 3 segundos por país (United Arab Emirates (AE))
Reproducciones de video de 3 segundos por país (The Bahamas (BS))
Reproducciones de video de 3 segundos por país (Bangladesh (BD))
Reproducciones de video de 3 segundos por país (Moldova (MD))
Reproducciones de video de 3 segundos por país (Algeria (DZ))
Reproducciones de video de 3 segundos por país (Ghana (GH))
Reproducciones de video de 3 segundos por país (Bulgaria (BG))
Reproducciones de video de 3 segundos por país (Finland (FI))
Reproducciones de video de 3 segundos por país (Denmark (DK))
Reproducciones de video de 3 segundos por país (Belarus (BY))
Reproducciones de video de 3 segundos por país (Slovenia (SI))
Reproducciones de video de 3 segundos por país (Hong Kong (HK))
Reproducciones de video de 3 segundos por país (Morocco (MA))
Reproducciones de video de 3 segundos por país (Israel (IL))
Reproducciones de video de 3 segundos por país (Guyana (GY))
Reproducciones de video de 3 segundos por país (Senegal (SN))
Reproducciones de video de 3 segundos por país (Latvia (LV))
Reproducciones de video de 3 segundos por país (Estonia (EE))
Reproducciones de video de 3 segundos por país (Niger (NE))
Reproducciones de video de 3 segundos por país (Serbia (RS))
Reproducciones de video de 3 segundos por país (Sri Lanka (LK))
Reproducciones de video de 3 segundos por país (Zambia (ZM))
Reproducciones de video de 3 segundos por país (Andorra (AD))
Reproducciones de video de 3 segundos por país (Iceland (IS))
Reproducciones de video de 3 segundos por país (Yemen (YE))
Reproducciones de video de 3 segundos por país (North Macedonia (MK))
Reproducciones de video de 3 segundos por país (Egypt (EG))
Reproducciones de video de 3 segundos por país (Kazakhstan (KZ))
Reproducciones de video de 3 segundos por país (Taiwan (TW))
Reproducciones de video de 3 segundos por país (Aruba (AW))
Reproducciones de video de 3 segundos por país (Luxembourg (LU))
Reproducciones de video de 3 segundos por país (Syria (SY))
Reproducciones de video de 3 segundos por país (Ethiopia (ET))
Reproducciones de video de 3 segundos por país (Jamaica (JM))
Reproducciones de video de 3 segundos por país (Guernsey (GG))
Reproducciones de video de 3 segundos por país (Oman (OM))
Reproducciones de video de 3 segundos por país (Turks and Caicos Islands (TC))
Reproducciones de video de 3 segundos por país (Haiti (HT))
Reproducciones de video de 3 segundos por país (Armenia (AM))
Reproducciones de video de 3 segundos por país (Jordan (JO))
Reproducciones de video de 3 segundos por país (Saudi Arabia (SA))
Reproducciones de video de 3 segundos por país (Bosnia and Herzegovina (BA))
Reproducciones de video de 3 segundos por país (Tunisia (TN))
Reproducciones de video de 3 segundos por país (Tajikistan (TJ))
Reproducciones de video de 3 segundos por país (Nepal (NP))
Reproducciones de video de 3 segundos por país (Martinique (MQ))
Reproducciones de video de 3 segundos por país (Georgia (GE))
Reproducciones de video de 3 segundos por país (Brunei (BN))
Reproducciones de video de 3 segundos por país (Malawi (MW))
Reproducciones de video de 3 segundos por país (Sint Maarten (SX))
Reproducciones de video de 3 segundos por país (Burkina Faso (BF))
Reproducciones de video de 3 segundos por país (Mayotte (YT))
Reproducciones de video de 3 segundos por país (Equatorial Guinea (GQ))
Reproducciones de video de 3 segundos por país (Côte d'Ivoire (CI))
Reproducciones de video de 3 segundos por país (Russia (RU))
Reproducciones de video de 3 segundos por país (Lebanon (LB))
Reproducciones de video de 3 segundos por país (Palestine (PS))
Reproducciones de video de 3 segundos por país (Libya (LY))